config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'title#index', as: 'title'

  resources :games, only: [:index, :show, :new, :create, :destroy]
  resources :players, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  has_one :player
end

app/models/plant.rb
class Plant < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :game
end

app/models/species.rb
class Species < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end

  def show
  end

  def new
    @game = Game.new
    @player = Player.new
  end

  def create
    @game = Game.new(game_params)

    if @game.save
      render 'new' #redirect_to 'title' # TODO route instead to actual game start!
    else
      render 'new'
    end
  end

  def destroy
  end

  private

  def game_params
    params.require(:game).permit(:name)
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/title_controller.rb
class TitleController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/game_helper.rb
module GameHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/title_helper.rb
module TitleHelper
end

app/views/games/_form.html.erb
<%= form_with model: @game do |f| %>

  <% if @game.errors.any? %>
    <div id="error_messages">
      <p>Sorry! We need a bit more information to get you started.</p>
      <ul>
        <% @game.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>What do you want to name your Jovian pale green dot?</p>
  <%= f.text_field :name, required:true, value:"Verdant Void Asteroid" %>

  <%= f.submit %>

<% end %>

app/views/games/destroy.html.erb
<h1>Game#destroy</h1>
<p>Find me in app/views/game/destroy.html.erb</p>

app/views/games/index.html.erb
<h1>Load Save</h1>
<header>
  <%= link_to 'Back to Title', title_path %>
</header>

<p> List saves here, including buttons to delete them w/ confirmation!</p>

app/views/games/new.html.erb
<h1>New Game</h1>

<header>
  <%= link_to 'Back to Title', title_path %>
</header>

<%= render 'form' %>

<p>TODO forms here, via partials!</p>

app/views/games/show.html.erb
<h1>Game#show</h1>
<p>Find me in app/views/game/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlantorioRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/show.html.erb
<h1>Player#show</h1>
<p>Find me in app/views/player/show.html.erb</p>

app/views/title/index.html.erb
<h1>Plantorio on (Space) Rails</h1>

<p>Grow your fortune among the stars!</p>

<%= link_to 'New Game', new_game_path %>

<%= link_to 'Load Game', games_path %>